services:
  ito-grpc-server:
    build: .
    ports:
      - '$PORT:$PORT'
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
    command: bun run start
    container_name: ito-server
    restart: always
    depends_on:
      - db
    environment:
      NODE_ENV: development

  db:
    image: postgres:16
    container_name: ito-postgres
    restart: always
    environment:
      POSTGRES_USER: '$DB_USER'
      POSTGRES_PASSWORD: '$DB_PASS'
      POSTGRES_DB: '$DB_NAME'
    ports:
      - '$DB_PORT:$DB_PORT'
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: ito-minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: '$S3_ACCESS_KEY_ID'
      MINIO_ROOT_PASSWORD: '$S3_SECRET_ACCESS_KEY'
    ports:
      - '9000:9000' # S3 API
      - '9001:9001' # MinIO Console
    volumes:
      - minio_data:/data
    healthcheck:
      test: ['CMD', 'mc', 'ready', 'local']
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  pgdata:
  minio_data:
