[package]
name = "active-application"
version = "0.1.0"
edition = "2024"

[dependencies]
active-win-pos-rs = "0.9.0"
serde = "1.0.219"
serde_json = "1.0.141"

[build-dependencies]
tauri-winres = "0.3.5"

[lints]
workspace = true
